#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(self):
  self(
    target            = 'pysc',
    features          = 'cxx cxxstlib pyembed venv_package',
    source            = [
                          'pysc.cpp',
                          'module.cpp',
                          'api/systemc.cpp',
                          'api/systemc.i',
                          'api/gc.cpp',
                          'api/gc.i',
                        ],
    pysource          = self.path.ant_glob(['**/*.py']),
    export_includes   = self.repository_root.abspath(),
    includes          = self.repository_root.abspath(),
    swig_flags        = '-c++ -python -Wall',
    use               = 'common GREENSOCS SYSTEMC TLM PYTHON BOOST',
    install_path      = '${PREFIX}/lib',
  )

  self(
      target          = 'pysc.1.test',
      features        = 'cxx cxxprogram pyembed',
      source          = 'tests/test1.cpp',
      use             = 'pysc GREENSOCS SYSTEMC TLM PYTHON BOOST',
  )
