#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
  self(
    target            = 'usi',
    features          = 'cxx cxxstlib pyembed venv_package',
    source            = [
                          'core/registry.cpp',
                          'core/module.cpp',
                          'core/api.cpp',

                          'api/systemc.cpp',
                          'api/systemc.i',
                          'api/parameter.cpp',
                          'api/parameter.i',
                          'api/usiobject.i',
                          'api/scireg.i',
                          'api/amba.i',
                          'api/mtrace.i',
                          'api/report.i',
                        ],
    pysource          = self.path.ant_glob(['**/*.py']),
    export_includes   = self.repository_root.abspath(),
    includes          = self.repository_root.abspath(),
    swig_flags        = '-c++ -python -Wall',
    use               = 'common GREENSOCS SYSTEMC TLM PYTHON BOOST',
    install_path      = '${PREFIX}/lib',
  )

