#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'
import sys

def build(self):
  self(
    target            = 'usi',
    features          = 'cxx cxxstlib pyembed venv_package',
    source            = [
                          'core/registry.cpp',
                          'core/module.cpp',
                          'core/api.cpp',
                          'api/systemc.cpp',
                          'api/systemc.i',
                          'api/sc_module.i',
                          'api/delegate.i',
                          'api/intrinsics.i',
                          'api/cci.cpp',
                          'api/cci.i',
#                          'api/scireg.i',
                          'api/amba.i',
                          'api/mtrace.i',
#                          'api/report.i',
#                          'api/registry.i',
                          'api/greensocket.i',
                        ],
    pysource          = self.path.ant_glob(['**/*.py']),
    export_includes   = self.repository_root.abspath(),
    export_defines    = "USI_PYVERSION_HEX={}".format(sys.hexversion),
    includes          = self.repository_root.abspath(),
    swig_flags        = '-c++ -python -Wall',
    use               = 'base PYTHON',
    install_path      = '${PREFIX}/lib',
  )

