top = '../..'

def build(self):
    self(
        target       = 'usiexec.platform',
        features     = 'cxx cprogram pyembed',
        source       = 'sc_main.cpp so_main.cpp',
        includes     = '.',
        use          = ['BOOST', 'usi', 'sr_iss', 'trap', 'common',
                        'sr_registry', 'sr_register', 'sr_report', 'sr_signal', 'base',
                        'AMBA', 'GREENSOCS', 'TLM', 'SYSTEMC', 'BOOST'
                       ],
    )
